data:  
    path: data/pets
    labels: 37
    images:
        count: 7349
        width: null
        height: null 
        channels: 3
    train_split: 0.8
        

model: 
    name: ResNet-34
    epochs: 20
    val_split: 0.1
    optimizer: 
        name: Adam
        lr: 0.001
        beta_1: 0.9
        beta_2: 0.999